"""add transaction_type and unit_price to transactions

Revision ID: 35d1818d0541
Revises: fabb7e848c2a
Create Date: 2026-05-19 22:59:54.401423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d1818d0541'
down_revision: Union[str, Sequence[str], None] = 'fabb7e848c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_type', sa.Enum('sale', 'adjustment'), nullable=False))
    op.add_column('transactions', sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'unit_price')
    op.drop_column('transactions', 'transaction_type')
    # ### end Alembic commands ###
